// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Replace these two lines:
// const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// With this (using your exact keys):
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://uypicoryafomuhkrptdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5cGljb3J5YWZvbXVoa3JwdGRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5OTYzMjcsImV4cCI6MjA4NjU3MjMyN30.0LFZfu0I01xQCtdBIiNfsIIYrwNBad4kYTP3Unyo5o4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});